# Configuration file for integration tests

general:
  debug:           false
  debugAddress:    '10.44.1.228:3000'  # Address which will be defined as DEBUG_ADDRESS in the virtual schemas
  bucketFsUrl:      http://localhost:2580/jars
  bucketFsPassword: public
  jdbcAdapterPath:  /buckets/bfsdefault/jars/virtualschema-jdbc-adapter-dist-1.4.0.jar

exasol:
  runIntegrationTests: true
  address:  localhost:8563
  user:     sys
  password: exasol


  
# Generic sql dialect is tested via MySQL
generic:
  runIntegrationTests: false
  jdbcDriverPath:      /buckets/bfsdefault/jars/mysql-connector-java-8.0.12.jar
  connectionString:    jdbc:mysql://localhost/virtual-schema-integration-test
  user:                virtual-schema-integration-test
  password:            password

oracle:
  runIntegrationTests: false
  jdbcDriverPath:      /buckets/mybucketfs/mybucket/oracle/ojdbc7.jar
  connectionString:    jdbc:oracle:thin:@oracle-host:1521:orcl
  user:                myuser
  password:            mypass


impala:
  runIntegrationTests: false
  connectionString:    jdbc:impala://impala-host:21050;AuthMech=0
  jdbcDriverPath:      /buckets/mybucketfs/mybucket/Cloudera_Impala_JDBC_2_5_28.1047_Driver/
  jdbcDriverJars:
    - hive_metastore.jar
    - hive_service.jar
    - ImpalaJDBC41.jar
    - libfb303-0.9.0.jar
    - libthrift-0.9.0.jar
    - log4j-1.2.14.jar
    - ql.jar
    - slf4j-api-1.5.11.jar
    - slf4j-log4j12-1.5.11.jar
    - TCLIServiceClient.jar
    - zookeeper-3.4.6.jar


kerberos:
  runIntegrationTests: false
  jdbcDriverPath:      /buckets/mybucketfs/mybucket/cloudera-hive-jdbc-driver/
  jdbcDriverJars:
    - HiveJDBC41.jar
    - hive_metastore.jar
    - hive_service.jar
    - libfb303-0.9.0.jar
    - libthrift-0.9.0.jar
    - log4j-1.2.14.jar
    - ql.jar
    - slf4j-api-1.5.11.jar
    - slf4j-log4j12-1.5.11.jar
    - TCLIServiceClient.jar
    - zookeeper-3.4.6.jar
  connectionString:    jdbc:hive2://hadoop-host.yourcompany.com:10000/;AuthMech=1;KrbRealm=YOURCOMPANY.COM;KrbHostFQDN=hadoop-host.yourcompany.com;KrbServiceName=hive
  user:                testuser@YOURCOMPANY.COM
  password:            ExaAuthType=Kerberos;X3xpYmRlZmF1bHRzXQpkZWZhdWx0X3JlYWxtID0gT01HLkRFVi5FWEFTT0wuQ09NCmRuc19jYW5vbmljYWxpemVfaG9zdG5hbWUgPSBmYWxzZQpkbnNfbG9va3VwX2tkYyA9IGZhbHNlCmRuc19sb29rdXBfcmVhbG0gPSBmYWxzZQp0aWNrZXRfbGlmZXRpbWUgPSA4NjQwMApyZW5ld19saWZldGltZSA9IDYwNDgwMApmb3J3YXJkYWJsZSA9IHRydWUKZGVmYXVsdF90Z3NfZW5jdHlwZXMgPSBhcmNmb3VyLWhtYWMKZGVmYXVsdF90a3RfZW5jdHlwZXMgPSBhcmNmb3VyLWhtYWMKcGVybWl0dGVkX2VuY3R5cGVzID0gYXJjZm91ci1obWFjCnVkcF9wcmVmZXJlbmNlX2xpbWl0ID0gMQpbcmVhbG1zXQpPTUcuREVWLkVYQVNPTC5DT00gPSB7CmtkYyA9IGhhZG9vcDAxLm9tZy5kZXYuZXhhc29sLmNvbQphZG1pbl9zZXJ2ZXIgPSBoYWRvb3AwMS5vbWcuZGV2LmV4YXNvbC5jb20KfQo=;BQIAAABBAAEAEk9NRy5ERVYuRVhBU09MLkNPTQAMaGFkb29wdGVzdGVyAAAAAVYo0X0BABcAEGuPtGr6sYdhUEbTqhYQ3E0=

hive:
  runIntegrationTests: false
  jdbcDriverPath:      /buckets/mybucketfs/mybucket/cloudera-hive-jdbc-driver/
  jdbcDriverJars:
    - HiveJDBC41.jar
    - hive_metastore.jar
    - hive_service.jar
    - libfb303-0.9.0.jar
    - libthrift-0.9.0.jar
    - log4j-1.2.14.jar
    - ql.jar
    - slf4j-api-1.5.11.jar
    - slf4j-log4j12-1.5.11.jar
    - TCLIServiceClient.jar
    - zookeeper-3.4.6.jar
  connectionString: jdbc:hive2://hive-host:10000
  user: user
  password: pass

